spring:
  datasource:
    url: jdbc:mysql://mysql:3306/AppMicroCompte?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: marakhib
    password: Marakhib
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: marakhib
    password: marakhib
  cloud:
    discovery:
      enabled: true
    eureka:
      client:
        service-url:
          defaultZone: http://eurekaserver:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
      instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 10
        lease-expiration-duration-in-seconds: 30
    stream:
      default-binder: rabbit
      bindings:
        debit-in-0:
          destination: debit.command
        credit-in-0:
          destination: credit.command
        compensate-in-0:
          destination: credit.compensate
        result-out-0:
          destination: operation.result
      rabbit:
        bindings:
          debit-in-0:
            consumer:
              autoBindDlq: true
    function:
      definition: debit;credit;depot;compensate
server:
  port: 8089