server:
  port: 8888
  forward-headers-strategy: framework

spring:
  application:
    name: gatewayServer

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # DAF Service
        - id: daf-service
          uri: lb://daf
          predicates:
            - Path=/citoyens/**,/daf/**
          filters:
            - RewritePath=/citoyens(?<segment>.*) /$\{segment}
            - RewritePath=/daf(?<segment>.*) /$\{segment}
        # Compte Service
        - id: compte-service
          uri: lb://compte
          predicates:
            - Path=/comptes/**
          filters:
            - RewritePath=/comptes(?<segment>.*) /$\{segment}
        # Transfert Service
        - id: transfert-service
          uri: lb://transfert
          predicates:
            - Path=/transferts/**
          filters:
            - RewritePath=/transferts(?<segment>.*) /$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    urls:
      - name: API
        url: https://apimicroservice.marakhib-global.com/v3/api-docs
  packages-to-scan: com.khouss.gatewayServer.config
